DELETE FROM Type_carte;
DELETE FROM Compte;
DELETE FROM Type_compte;
DELETE FROM Personne;
DELETE FROM Agence;
DELETE FROM Banque;

INSERT INTO Banque VALUES (001, 'FirstBank', 'FST BK BIC');
INSERT INTO Banque VALUES (002, 'SecondBank', 'SND BK BIC');
INSERT INTO Banque VALUES (003, 'ThirdBank', 'THRD BK BIC');
INSERT INTO Agence VALUES (0001, 'FirstAgenceFstBK', 001);
INSERT INTO Agence VALUES (0002, 'SndAgenceFstBK', 001);
INSERT INTO Agence VALUES (0003, 'ThirdAgenceFstBK', 001);
INSERT INTO Agence VALUES (0011, 'FirstAgenceSndBK', 002);
INSERT INTO Agence VALUES (0012, 'SecondAgenceSndBK', 002);
INSERT INTO Personne VALUES (1,'Castellanos','Alejandro','12/17/1985','M','0');
INSERT INTO Personne VALUES (2,'Huam','Erica','08/23/1990','M','0');
INSERT INTO Personne VALUES (3,'Jamal','Meryam','05/15/1990','M','0');
INSERT INTO Personne VALUES (4,'Tonnelier','Jerome','07/23/1988','M','0');
INSERT INTO Personne VALUES (5, 'Maimaiti', 'Amina','06/28/1984','C','0');
INSERT INTO Type_compte VALUES (1,1,0,'Epargne');
INSERT INTO Type_compte VALUES (2,1,0,'Courant');
INSERT INTO Type_compte VALUES (3,2,1, 'J Epargne');
INSERT INTO Type_compte VALUES (4,2,1, 'J Courant');
--INSERT INTO Compte VALUES ('moncompte1',0,400,1,1,'ibanalejo',0002);
--INSERT INTO Compte VALUES ('moncompte2',2000,0,3,2,'ibanmeryam',0011);
--INSERT INTO Compte VALUES ('moncompte3',0,400,2,1,'ibanerica',0012);
INSERT INTO Type_carte VALUES (1, 'retrait', 0, 0);
INSERT INTO Type_carte VALUES (2, 'paiement', 0, 8);
INSERT INTO Type_carte VALUES (3, 'credit', 0, 12);
INSERT INTO Type_carte VALUES (4, 'retrait', 1, 8);
INSERT INTO Type_carte VALUES (5, 'paiement', 1, 12);
INSERT INTO Type_carte VALUES (6, 'credit', 1, 20);